version: 2.0.{build}.0

install:
  - choco install -y wget
  - wget -q https://download.microsoft.com/download/4/6/1/46116DFF-29F9-4FF8-94BF-F9BE05BE263B/packages/DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe
  - DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe /install /quiet /log dotnetinstall.log
  - ps: Push-AppveyorArtifact "dotnetinstall.log"

environment:
  NuGetApiKey:
    secure: uNF4gY8KN67ODxKkGPBIz+5MDdf3MRtz4Vi+9McPhWYi4Z6YMQvOcTQRWZYd/N9b

assembly_info:
  patch: true
  file: Shared\SharedAssemblyInfo.cs
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build_script:
  - cmd: cd SharpAdbClient
  - cmd: dotnet restore
  - cmd: dotnet build -c Release --version-suffix beta%APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet pack -c Release --version-suffix beta%APPVEYOR_BUILD_NUMBER%

on_success:
  - ps: Push-AppveyorArtifact "bin\Release\SharpAdbClient.2.1.0-beta$($env:APPVEYOR_BUILD_NUMBER).nupkg"
  - ps: Push-AppveyorArtifact "bin\Release\SharpAdbClient.2.1.0-beta$($env:APPVEYOR_BUILD_NUMBER).symbols.nupkg"

test:
  categories:
    except:
      - IntegrationTest

test_script: 
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:".\SharpAdbClient.Tests\bin\Release\SharpAdbClient.Tests.dll /logger:Appveyor /testcasefilter:TestCategory!=IntegrationTest" -filter:"+[SharpAdbClient]*  -[SharpAdbClient]SharpAdbClient.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\SharpAdbClient.coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "SharpAdbClient.Coverage.xml"

nuget:
  project_feed: true
  account_feed: true

