image: Visual Studio 2017

version: 2.2.{build}.0

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\SharpAdbClient
  - cmd: dotnet restore
  - cmd: dotnet build -c Release
  - cmd: dotnet pack -c Release

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\SharpAdbClient.Tests\
  - cmd: dotnet restore
  - cmd: dotnet build
  - cmd: dotnet test SharpAdbClient.Tests.csproj --filter "TestCategory!=IntegrationTest & TestCategory!=PerformanceTest" "--logger:trx;LogFileName=testresults.trx" /p:CollectCoverage=true
  - ps: '& (Join-Path $env:APPVEYOR_BUILD_FOLDER "appveyor-testresults.ps1")'

artifacts:
  - path: SharpAdbClient\bin\Release\SharpAdbClient.*.nupkg

deploy:
  provider: NuGet
  on:
    branch: master
  api_key:
    secure: 9mlPwPUoNfB6CeV5y319zv0v9dl16VhKKAbdrIiPYQD0W1ogYzBZ04X9kjuNMo5I
  skip_symbols: true
