version: 2.0.{build}.0

environment:
  NuGetApiKey:
    secure: uNF4gY8KN67ODxKkGPBIz+5MDdf3MRtz4Vi+9McPhWYi4Z6YMQvOcTQRWZYd/N9b

assembly_info:
  patch: true
  file: Shared\SharedAssemblyInfo.cs
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build_script:
  - msbuild SharpAdbClient.sln /p:Configuration=Release /p:Platform="Any CPU" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

on_success:
  - cmd: nuget pack SharpAdbClient.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - ps: Push-AppveyorArtifact "madb.$($env:APPVEYOR_BUILD_VERSION).nupkg"

test:
  categories:
    except:
      - IntegrationTest

test_script: 
  - .\packages\OpenCover.4.6.210-rc\tools\OpenCover.Console.exe -register:user -target:"c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:".\SharpAdbClient.Tests\bin\Release\SharpAdbClient.Tests.dll /logger:Appveyor /testcasefilter:TestCategory!=IntegrationTest" -filter:"+[SharpAdbClient]*  -[SharpAdbClient]SharpAdbClient.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\SharpAdbClient.coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "SharpAdbClient.Coverage.xml"

nuget:
  project_feed: true
  account_feed: true

